[package]
name = "xtask"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "xtask"
path = "main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
zip.workspace = true
