[package]
name = "nrtm"
version.workspace = true
edition.workspace = true

[features]
openssl = ["dep:openssl"]

[dependencies]
anyhow = "1.0.75"
once_cell = "1.18.0"
clap = { version = "4.4.6", features = ["derive"] }
futures-util = "0.3.28"
tokio = { version = "1.32.0", features = ["full"] }
reqwest = { version = "0.11.22", features = ["stream"] }
indicatif = "0.17.5"
zip = "0.6.6"
tar = "0.4.40"
flate2 = "1.0.27"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
semver = { version = "1.0.19", features = ["serde"] }
regex = "1.9.6"
which = "4.4.2"

openssl = { version = "0.10", features = ["vendored"], optional = true }
