name: Auto Fix

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Rust files
        uses: Swatinem/rust-cache@v2

      - name: Create out.zip
        run: cargo xtask build --dist

      - name: Format Rust code
        run: |
          cargo clippy --workspace --fix --allow-dirty
          cargo fmt

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: apply formatter/linter changes"
