name: CI

on:
  pull_request:
    branches:
      - main

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust toolchains
        uses: Swatinem/rust-cache@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Lint
        if: matrix.os == 'ubuntu-latest'
        run: |
          rustup component add clippy
          cargo clippy

      - name: Build
        run: python ./build.py

      - name: Build for musl target
        if: matrix.os == 'ubuntu-latest'
        run: python ./build.py --target x86_64-unknown-linux-musl

      - name: Test
        run: cargo test
