name: CI

on:
  pull_request:
    branches:
      - main
      - '!release'

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust toolchains
        uses: Swatinem/rust-cache@v2

      - name: Setup Zig
        if: matrix.os == 'ubuntu-latest'
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0

      - name: Install cargo-zigbuild
        if: matrix.os == 'ubuntu-latest'
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-zigbuild

      - name: Build
        run: cargo xtask build --dist

      - name: Build for musl target
        if: matrix.os == 'ubuntu-latest'
        run: cargo xtask build --dist -- --target x86_64-unknown-linux-musl

      - name: Lint
        if: matrix.os == 'ubuntu-latest'
        run: |
          rustup component add clippy
          cargo clippy

      - name: Test
        run: cargo test
