name: Release

on:
  push:
    tags:
      - 'v*'

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-apple-darwin
            os: macos-11
          - target: aarch64-apple-darwin
            os: macos-11
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust files
        uses: Swatinem/rust-cache@v2

      - name: Setup Zig
        if: matrix.target == 'x86_64-unknown-linux-musl'
        uses: goto-bus-stop/setup-zig@2
        with:
          version: 0.11.0

      - name: Install cargo-zigbuild
        if: matrix.target == 'x86_64-unknown-linux-musl'
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-zigbuild

      - name: Create dist
        run: cargo xtask build --dist -- --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ matrix.target }}
          path: './out-${{ matrix.target }}/nrtm-installer-${{ matrix.target }}**'

  release:
    needs: ["build"]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist-x86_64-pc-windows-msvc
          path: dist
      - uses: actions/download-artifact@v3
        with:
          name: dist-aarch64-apple-darwin
          path: dist
      - uses: actions/download-artifact@v3
        with:
          name: dist-x86_64-apple-darwin
          path: dist
      - uses: actions/download-artifact@v3
        with:
          name: dist-x86_64-unknown-linux-musl
          path: dist

      - run: ls -al ./dist

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: './dist/*'
          name: ${{ env.TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
